Scripts: using a diffrent formatter that doens't mess up case

diff --git a/Scripts/.local/bin/lsix b/Scripts/.local/bin/lsix
--- a/Scripts/.local/bin/lsix
+++ b/Scripts/.local/bin/lsix
@@ -10,16 +10,15 @@
 
 # See end of file for USAGE.
 
-
 # The following defaults may be overridden if autodetection succeeds.
 numcolors=16     # Default number of colors in the palette.
 background=white # Default montage background.
 foreground=black # Default text color.
-width=800	 # Default width of screen in pixels.
+width=800        # Default width of screen in pixels.
 
 # Feel free to edit these defaults to your liking.
-tilesize=120	       # Width and height of each tile in the montage.
-tilewidth=$tilesize    # (or specify separately, if you prefer)
+tilesize=120        # Width and height of each tile in the montage.
+tilewidth=$tilesize # (or specify separately, if you prefer)
 tileheight=$tilesize
 
 # If you get questionmarks for Unicode filenames, try using a different font.
@@ -29,234 +28,239 @@ tileheight=$tilesize
 #fontfamily=Mincho			# Wide coverage, comes with MS Windows
 
 # Default font size is based on width of each tile in montage.
-fontsize=$((tilewidth/10))
+fontsize=$((tilewidth / 10))
 #fontsize=16		     # (or set the point size directly, if you prefer)
 
-timeout=0.25		    # How long to wait for terminal to respond
-			    # to a control sequence (in seconds).
+timeout=0.25 # How long to wait for terminal to respond
+# to a control sequence (in seconds).
 
 # Sanity checks and compatibility
 if [[ ${BASH_VERSINFO[0]} -eq 3 ]]; then
-    if bash --version | head -1 | grep -q "version 3"; then
-	cat <<-EOF >&2
-	Error: The version of Bash is extremely out of date.
-	(2007, the same year Steve Jobs announced the iPhone!)
+	if bash --version | head -1 | grep -q "version 3"; then
+		cat <<-EOF >&2
+			Error: The version of Bash is extremely out of date.
+			(2007, the same year Steve Jobs announced the iPhone!)
 
-	This is almost always due to Apple's MacOS being silly.
-	Please let Apple know that their users expect current UNIX tools.
+			This is almost always due to Apple's MacOS being silly.
+			Please let Apple know that their users expect current UNIX tools.
 
-	In the meantime, try using "brew install bash".
-	EOF
-	exit 1
-    else
-	exec bash "$0" "$@"  || echo "Exec failed" >&2
-	exit 1
-    fi
+			In the meantime, try using "brew install bash".
+		EOF
+		exit 1
+	else
+		exec bash "$0" "$@" || echo "Exec failed" >&2
+		exit 1
+	fi
 fi
 
 if ! command -v montage >/dev/null; then
-    echo "Please install ImageMagick" >&2
-    exit 1
+	echo "Please install ImageMagick" >&2
+	exit 1
 fi
 
-shopt -s expand_aliases		# Allow aliases for working around quirks.
+shopt -s expand_aliases # Allow aliases for working around quirks.
 
 if command -v gsed >/dev/null; then
-    alias sed=gsed		# Use GNU sed for MacOS & BSD.
+	alias sed=gsed # Use GNU sed for MacOS & BSD.
 fi
 
 if [[ "$COMSPEC" ]]; then
-    alias convert="magick convert" # Shun MS Windows' "convert" command.
+	alias convert="magick convert" # Shun MS Windows' "convert" command.
 fi
-    
+
 cleanup() {
-    echo -n $'\e\\'		# Escape sequence to stop SIXEL.
-    stty echo			# Reset terminal to show characters.
-    exit 0
+	echo -n $'\e\\' # Escape sequence to stop SIXEL.
+	stty echo       # Reset terminal to show characters.
+	exit 0
 }
 trap cleanup SIGINT SIGHUP SIGABRT EXIT
 
 autodetect() {
-    # Various terminal automatic configuration routines.
+	# Various terminal automatic configuration routines.
 
-    # Don't show escape sequences the terminal doesn't understand.
-    stty -echo			# Hush-a Mandara Ni Pari
+	# Don't show escape sequences the terminal doesn't understand.
+	stty -echo # Hush-a Mandara Ni Pari
 
-    # IS TERMINAL SIXEL CAPABLE?		# Send Device Attributes
-    IFS=";?c" read -a REPLY -s -t 1 -d "c" -p $'\e[c' >&2
-    for code in "${REPLY[@]}"; do
-	if [[ $code == "4" ]]; then
-	    hassixel=yup
-	    break
+	# IS TERMINAL SIXEL CAPABLE?		# Send Device Attributes
+	IFS=";?c" read -a REPLY -s -t 1 -d "c" -p $'\e[c' >&2
+	for code in "${REPLY[@]}"; do
+		if [[ $code == "4" ]]; then
+			hassixel=yup
+			break
+		fi
+	done
+
+	# YAFT is vt102 compatible, cannot respond to vt220 escape sequence.
+	if [[ "$TERM" == yaft* ]]; then hassixel=yeah; fi
+
+	if [[ -z "$hassixel" && -z "$LSIX_FORCE_SIXEL_SUPPORT" ]]; then
+		cat <<-EOF >&2
+			Error: Your terminal does not report having sixel graphics support.
+
+			Please use a sixel capable terminal, such as xterm -ti vt340, or
+			ask your terminal manufacturer to add sixel support.
+
+			You may test your terminal by viewing a single image, like so:
+
+				convert  foo.jpg  -geometry 800x480  sixel:-
+
+			If your terminal actually does support sixel, please file a bug
+			report at http://github.com/hackerb9/lsix/issues
+		EOF
+		read -s -t 1 -d "c" -p $'\e[c' >&2
+		if [[ "$REPLY" ]]; then
+			echo
+			cat -v <<<"Please mention device attribute codes: ${REPLY}c"
+		fi
+
+		exit 1
 	fi
-    done
 
-    # YAFT is vt102 compatible, cannot respond to vt220 escape sequence.
-    if [[ "$TERM" == yaft* ]]; then hassixel=yeah; fi
+	# SIXEL SCROLLING (~DECSDM) is now presumed to be enabled.
+	# See https://github.com/hackerb9/lsix/issues/41 for details.
 
-    if [[ -z "$hassixel" && -z "$LSIX_FORCE_SIXEL_SUPPORT" ]]; then
-	cat <<-EOF >&2
-	Error: Your terminal does not report having sixel graphics support.
-
-	Please use a sixel capable terminal, such as xterm -ti vt340, or
-	ask your terminal manufacturer to add sixel support.
-
-	You may test your terminal by viewing a single image, like so:
-
-		convert  foo.jpg  -geometry 800x480  sixel:-
-
-	If your terminal actually does support sixel, please file a bug
-	report at http://github.com/hackerb9/lsix/issues
-	EOF
-	read -s -t 1 -d "c" -p $'\e[c' >&2
-	if [[ "$REPLY" ]]; then
-	    echo
-	    cat -v <<< "Please mention device attribute codes: ${REPLY}c"
-	fi
-
-	exit 1
-    fi
-
-    # SIXEL SCROLLING (~DECSDM) is now presumed to be enabled.
-    # See https://github.com/hackerb9/lsix/issues/41 for details.
-
-    # TERMINAL COLOR AUTODETECTION.
-    # Find out how many color registers the terminal has
-    IFS=";"  read -a REPLY -s -t ${timeout} -d "S" -p $'\e[?1;1;0S' >&2
-    [[ ${REPLY[1]} == "0" ]] && numcolors=${REPLY[2]}
-
-    # YAFT is vt102 compatible, cannot respond to vt220 escape sequence.
-    if [[ "$TERM" == yaft* ]]; then numcolors=256; fi
-
-    # Increase colors, if needed
-    if [[ $numcolors -lt 256 ]]; then
-	# Attempt to set the number of colors to 256.
-	# This will work for xterm, but fail on a real vt340.
-	IFS=";"  read -a REPLY -s -t ${timeout} -d "S" -p $'\e[?1;3;256S' >&2
+	# TERMINAL COLOR AUTODETECTION.
+	# Find out how many color registers the terminal has
+	IFS=";" read -a REPLY -s -t ${timeout} -d "S" -p $'\e[?1;1;0S' >&2
 	[[ ${REPLY[1]} == "0" ]] && numcolors=${REPLY[2]}
-    fi
 
-    # Query the terminal background and foreground colors.
-    IFS=";:/"  read -a REPLY -r -s -t ${timeout} -d "\\" -p $'\e]11;?\e\\' >&2
-    if [[ ${REPLY[1]} =~ ^rgb ]]; then
-	# Return value format: $'\e]11;rgb:ffff/0000/ffff\e\\'.
-	# ImageMagick wants colors formatted as #ffff0000ffff.
-	background='#'${REPLY[2]}${REPLY[3]}${REPLY[4]%%$'\e'*}
-	IFS=";:/"  read -a REPLY -r -s -t ${timeout} -d "\\" -p $'\e]10;?\e\\' >&2
+	# YAFT is vt102 compatible, cannot respond to vt220 escape sequence.
+	if [[ "$TERM" == yaft* ]]; then numcolors=256; fi
+
+	# Increase colors, if needed
+	if [[ $numcolors -lt 256 ]]; then
+		# Attempt to set the number of colors to 256.
+		# This will work for xterm, but fail on a real vt340.
+		IFS=";" read -a REPLY -s -t ${timeout} -d "S" -p $'\e[?1;3;256S' >&2
+		[[ ${REPLY[1]} == "0" ]] && numcolors=${REPLY[2]}
+	fi
+
+	# Query the terminal background and foreground colors.
+	IFS=";:/" read -a REPLY -r -s -t ${timeout} -d "\\" -p $'\e]11;?\e\\' >&2
 	if [[ ${REPLY[1]} =~ ^rgb ]]; then
-	    foreground='#'${REPLY[2]}${REPLY[3]}${REPLY[4]%%$'\e'*}
-	    # Check for "Reverse Video" (DECSCNM screen mode).
-	    IFS=";?$"  read -a REPLY -s -t ${timeout} -d "y" -p $'\e[?5$p'
-	    if [[ ${REPLY[2]} == 1 || ${REPLY[2]} == 3 ]]; then
-		temp=$foreground
-		foreground=$background
-		background=$temp
-	    fi
+		# Return value format: $'\e]11;rgb:ffff/0000/ffff\e\\'.
+		# ImageMagick wants colors formatted as #ffff0000ffff.
+		background='#'${REPLY[2]}${REPLY[3]}${REPLY[4]%%$'\e'*}
+		IFS=";:/" read -a REPLY -r -s -t ${timeout} -d "\\" -p $'\e]10;?\e\\' >&2
+		if [[ ${REPLY[1]} =~ ^rgb ]]; then
+			foreground='#'${REPLY[2]}${REPLY[3]}${REPLY[4]%%$'\e'*}
+			# Check for "Reverse Video" (DECSCNM screen mode).
+			IFS=";?$" read -a REPLY -s -t ${timeout} -d "y" -p $'\e[?5$p'
+			if [[ ${REPLY[2]} == 1 || ${REPLY[2]} == 3 ]]; then
+				temp=$foreground
+				foreground=$background
+				background=$temp
+			fi
+		fi
 	fi
-    fi
-    # YAFT is vt102 compatible, cannot respond to vt220 escape sequence.
-    if [[ "$TERM" == yaft* ]]; then background=black; foreground=white; fi
-
-    # Send control sequence to query the sixel graphics geometry to
-    # find out how large of a sixel image can be shown.
-    IFS=";"  read -a REPLY -s -t ${timeout} -d "S" -p $'\e[?2;1;0S' >&2
-    if [[ ${REPLY[2]} -gt 0 ]]; then
-	width=${REPLY[2]}
-    else
-	# Nope. Fall back to dtterm WindowOps to approximate sixel geometry.
-	IFS=";" read -a REPLY -s -t ${timeout} -d "t" -p $'\e[14t' >&2
-	if [[ $? == 0  &&  ${REPLY[2]} -gt 0 ]]; then
-	    width=${REPLY[2]}
+	# YAFT is vt102 compatible, cannot respond to vt220 escape sequence.
+	if [[ "$TERM" == yaft* ]]; then
+		background=black
+		foreground=white
 	fi
-    fi
 
-    # BUG WORKAROUND: XTerm cannot show images wider than 1000px.
-    # Remove this hack once XTerm gets fixed. Last checked: XTerm(344)
-    if [[ $TERM =~ xterm && $width -ge 1000 ]]; then  width=1000; fi
+	# Send control sequence to query the sixel graphics geometry to
+	# find out how large of a sixel image can be shown.
+	IFS=";" read -a REPLY -s -t ${timeout} -d "S" -p $'\e[?2;1;0S' >&2
+	if [[ ${REPLY[2]} -gt 0 ]]; then
+		width=${REPLY[2]}
+	else
+		# Nope. Fall back to dtterm WindowOps to approximate sixel geometry.
+		IFS=";" read -a REPLY -s -t ${timeout} -d "t" -p $'\e[14t' >&2
+		if [[ $? == 0 && ${REPLY[2]} -gt 0 ]]; then
+			width=${REPLY[2]}
+		fi
+	fi
 
-    # Space on either side of each tile is less than 0.5% of total screen width
-    tilexspace=$((width/201))
-    tileyspace=$((tilexspace/2))
-    # Figure out how many tiles we can fit per row. ("+ 1" is for -shadow).
-    numtiles=$((width/(tilewidth + 2*tilexspace + 1)))
+	# BUG WORKAROUND: XTerm cannot show images wider than 1000px.
+	# Remove this hack once XTerm gets fixed. Last checked: XTerm(344)
+	if [[ $TERM =~ xterm && $width -ge 1000 ]]; then width=1000; fi
+
+	# Space on either side of each tile is less than 0.5% of total screen width
+	tilexspace=$((width / 201))
+	tileyspace=$((tilexspace / 2))
+	# Figure out how many tiles we can fit per row. ("+ 1" is for -shadow).
+	numtiles=$((width / (tilewidth + 2 * tilexspace + 1)))
 }
 
 main() {
-    # Discover and setup the terminal
-    autodetect
+	# Discover and setup the terminal
+	autodetect
 
-    if [[ $# == 0 ]]; then
-	# No command line args? Use a sorted list of image files in CWD.
-	shopt -s nullglob nocaseglob nocasematch
-	set -- *{jpg,jpeg,png,gif,webp,tiff,tif,p?m,x[pb]m,bmp,ico,svg,eps}
-	[[ $# != 0 ]] || exit
-	readarray -t < <(printf "%s\n" "$@" | sort)
+	if [[ $# == 0 ]]; then
+		# No command line args? Use a sorted list of image files in CWD.
+		shopt -s nullglob nocaseglob nocasematch
+		set -- *{jpg,jpeg,png,gif,webp,tiff,tif,p?m,x[pb]m,bmp,ico,svg,eps}
+		[[ $# != 0 ]] || exit
+		readarray -t < <(printf "%s\n" "$@" | sort)
 
-	# Only show first frame of animated GIFs if filename not specified.
-	for x in ${!MAPFILE[@]}; do
-	    if [[ ${MAPFILE[$x]} =~ gif$ ]]; then
-		MAPFILE[$x]="${MAPFILE[$x]}[0]"
-	    fi
+		# Only show first frame of animated GIFs if filename not specified.
+		for x in ${!MAPFILE[@]}; do
+			if [[ ${MAPFILE[$x]} =~ gif$ ]]; then
+				MAPFILE[$x]="${MAPFILE[$x]}[0]"
+			fi
+		done
+		set -- "${MAPFILE[@]}"
+	else
+		# Command line args specified. Check for directories.
+		lsix=$(realpath "$0")
+		for arg; do
+			if [ -d "$arg" ]; then
+				echo Recursing on $arg
+				(
+					cd "$arg"
+					$lsix
+				)
+			else
+				nodirs+=("$arg")
+			fi
+		done
+		set -- "${nodirs[@]}"
+	fi
+
+	# Resize on load: Save memory by appending this suffix to every filename.
+	resize="[${tilewidth}x${tileheight}]"
+
+	imoptions="-tile ${numtiles}x1"                                                 # Each montage is 1 row x $numtiles columns
+	imoptions+=" -geometry ${tilewidth}x${tileheight}>+${tilexspace}+${tileyspace}" # Size of each tile and spacing
+	imoptions+=" -background $background -fill $foreground"                         # Use terminal's colors
+	imoptions+=" -auto-orient "                                                     # Properly rotate JPEGs from cameras
+	if [[ $numcolors -gt 16 ]]; then
+		imoptions+=" -shadow " # Just for fun :-)
+	fi
+
+	# See top of this file to change fontfamily and fontsize.
+	[[ "$fontfamily" ]] && imoptions+=" -font $fontfamily "
+	[[ "$fontsize" ]] && imoptions+=" -pointsize $fontsize "
+
+	# Create and display montages one row at a time.
+	while [ $# -gt 0 ]; do
+		# While we still have images to process...
+		onerow=()
+		goal=$(($# - numtiles)) # How many tiles left after this row
+		while [ $# -gt 0 -a $# -gt $goal ]; do
+			len=${#onerow[@]}
+			onerow[len++]="-label"
+			onerow[len++]=$(processlabel "$1")
+			onerow[len++]="file://$1"
+			shift
+		done
+		montage "${onerow[@]}" $imoptions gif:- |
+			convert - -colors $numcolors sixel:-
 	done
-	set -- "${MAPFILE[@]}"
-    else
-	# Command line args specified. Check for directories.
-	lsix=$(realpath "$0")
-	for arg; do
-	    if [ -d "$arg" ]; then
-		echo Recursing on $arg
-		(cd "$arg"; $lsix)
-	    else
-		nodirs+=("$arg")
-	    fi
-	done
-	set -- "${nodirs[@]}"
-    fi
-
-
-    # Resize on load: Save memory by appending this suffix to every filename.
-    resize="[${tilewidth}x${tileheight}]"
-
-    imoptions="-tile ${numtiles}x1" # Each montage is 1 row x $numtiles columns
-    imoptions+=" -geometry ${tilewidth}x${tileheight}>+${tilexspace}+${tileyspace}" # Size of each tile and spacing
-    imoptions+=" -background $background -fill $foreground" # Use terminal's colors
-    imoptions+=" -auto-orient "	# Properly rotate JPEGs from cameras
-    if [[ $numcolors -gt 16 ]]; then
-	imoptions+=" -shadow "		# Just for fun :-)
-    fi
-
-    # See top of this file to change fontfamily and fontsize.
-    [[ "$fontfamily" ]]  &&  imoptions+=" -font $fontfamily "
-    [[ "$fontsize" ]] &&     imoptions+=" -pointsize $fontsize "
-
-    # Create and display montages one row at a time.
-    while [ $# -gt 0 ]; do
-	# While we still have images to process...
-	onerow=()
-	goal=$(($# - numtiles)) # How many tiles left after this row
-	while [ $# -gt 0  -a  $# -gt $goal ]; do
-	    len=${#onerow[@]}
-	    onerow[len++]="-label"
-	    onerow[len++]=$(processlabel "$1")
-	    onerow[len++]="file://$1"
-	    shift
-	done
-	montage "${onerow[@]}"  $imoptions gif:-  \
-	    | convert - -colors $numcolors sixel:-
-    done
 }
 
 processlabel() {
-    # This routine is all about appeasing ImageMagick.
-    # 1. Remove silly [0] suffix and : prefix.
-    # 2. Quote percent backslash, and at sign.
-    # 3. Replace control characters with question marks.
-    # 4. If a filename is too long, remove extension (.jpg).
-    # 5. Split long filenames with newlines (recursively)
-    span=15			# filenames longer than span will be split
-    echo -n "$1" |
-	sed 's|^:||; s|\[0]$||;' | tr '[:cntrl:]' '?' |
-	awk -v span=$span -v ORS=""  '
+	# This routine is all about appeasing ImageMagick.
+	# 1. Remove silly [0] suffix and : prefix.
+	# 2. Quote percent backslash, and at sign.
+	# 3. Replace control characters with question marks.
+	# 4. If a filename is too long, remove extension (.jpg).
+	# 5. Split long filenames with newlines (recursively)
+	span=15 # filenames longer than span will be split
+	echo -n "$1" |
+		sed 's|^:||; s|\[0]$||;' | tr '[:cntrl:]' '?' |
+		awk -v span=$span -v ORS="" '
 	function halve(s,      l,h) {	# l and h are locals
 	    l=length(s);  h=int(l/2);
 	    if (l <= span) { return s; }
@@ -267,7 +271,7 @@ processlabel() {
 	  print halve($0);
 	}
 	' |
-	sed 's|%|%%|g; s|\\|\\\\|g; s|@|\\@|g;'
+		sed 's|%|%%|g; s|\\|\\\\|g; s|@|\\@|g;'
 }
 
 ####
@@ -277,7 +281,6 @@ main "$@"
 # Send an escape sequence and wait for a response from the terminal
 # so that the program won't quit until images have finished transferring.
 read -s -t 60 -d "c" -p $'\e[c' >&2
-
 
 ######################################################################
 # NOTES:
diff --git a/Scripts/.local/bin/sixcat b/Scripts/.local/bin/sixcat
--- a/Scripts/.local/bin/sixcat
+++ b/Scripts/.local/bin/sixcat
@@ -18,17 +18,16 @@
 # All the other lines are bells and whistles, mostly to make the image
 # look better by increasing the number of colors available.
 
-
 ######################################################################
 # Configuration
 ######################################################################
 
 # Number of colors in the terminal's sixel palette.
 # (But also see the -x and -n options).
-default_numcolors=16	     # Genuine vt340's had a 16-color palette.
+default_numcolors=16 # Genuine vt340's had a 16-color palette.
 
 # Maximum image size is terminal dependent, so we have to guess.
-geometry="-geometry 800x480>"		# this was the actual vt340 resolution
+geometry="-geometry 800x480>" # this was the actual vt340 resolution
 #geometry="-geometry 800x800>"		# allows for portrait orientation
 #geometry="-geometry 1000x1000>"	# maximum allowed in xterm322
 
@@ -42,13 +41,12 @@ dither="-dither floyd-steinberg"
 # increased for slow links (e.g., RS232C).
 timeout=0.1
 
-
 ######################################################################
-# Helper functions 
+# Helper functions
 ######################################################################
 
 usage() {
-    cat <<EOF
+	cat <<EOF
 Usage: $(basename $0) [-x|-X|-n INTEGER] <imagefiles...>
 
         -x: Force the use of xterm escape sequences to detect and
@@ -70,214 +68,207 @@ in the top left instead of scrolling all the frames as multiple images.
 EOF
 }
 
-
 # Some functions to deal with checking and changing the number of
 # colors the terminal can show. Likely xterm specific, but YMMV.
 
 getnumcolors() {
-    # Query xterm for the palette size and print it.
-    # (Negative numbers indicate errors.)
-    colors 1 0
+	# Query xterm for the palette size and print it.
+	# (Negative numbers indicate errors.)
+	colors 1 0
 }
 
 resetnumcolors() {
-    # Reset xterm back to its default number of colors.
-    # Print the new number of colors (negative if an error occurred.)
-    colors 2 0
+	# Reset xterm back to its default number of colors.
+	# Print the new number of colors (negative if an error occurred.)
+	colors 2 0
 }
 
 setnumcolors() {
-    # Request xterm to change the number of colors in its palette. 
-    # Print the new number of colors (negative if an error occurred.)
-    colors 3 $1
+	# Request xterm to change the number of colors in its palette.
+	# Print the new number of colors (negative if an error occurred.)
+	colors 3 $1
 }
 
 colors() {
-    # Send an xterm escape code request in the form: ^[[?1;3;1024S
-    # Print the response value (or a negative number if an error occurs)
-    csi=$'\e['
-    action=$1                 # Action. 1 to get, 2 to reset, 3 to set
-    value=$2                  # Number of colors to set
-    returnvalue=-1
+	# Send an xterm escape code request in the form: ^[[?1;3;1024S
+	# Print the response value (or a negative number if an error occurs)
+	csi=$'\e['
+	action=$1 # Action. 1 to get, 2 to reset, 3 to set
+	value=$2  # Number of colors to set
+	returnvalue=-1
 
-    # Raw response is in the same form as request: ^[[?1;0;1024S
-    # Let's parse it to be more manageable.
-    IFS=";" \
-       read -a REPLY -s -t $timeout -d "S" \
-       	    -p "${csi}?1;${action};${value}S"
+	# Raw response is in the same form as request: ^[[?1;0;1024S
+	# Let's parse it to be more manageable.
+	IFS=";" \
+		read -a REPLY -s -t $timeout -d "S" \
+		-p "${csi}?1;${action};${value}S"
 
-    if [[ $? != 0 || ${#REPLY} == 0 ]]; then
-	# No response to VT escape sequence. Maybe you are not an xterm?
-	# Or, perhaps timeout is too short?
-	returnvalue=-2
-    elif [[ "${REPLY[1]}" == "3" ]]; then
-	# Response code 3 means error. Likely too many colors requested.
-	returnvalue=-3
-    elif [[ "${REPLY[1]}" == "0" ]] ; then
-	# 0 means okay. Yay!
-	returnvalue=${REPLY[2]}
-    else
-     	# If we get here, response was not in the format we expected.
-	# Perhaps user typed during xterm response? Or cosmic rays?
-	returnvalue=-4
-    fi
+	if [[ $? != 0 || ${#REPLY} == 0 ]]; then
+		# No response to VT escape sequence. Maybe you are not an xterm?
+		# Or, perhaps timeout is too short?
+		returnvalue=-2
+	elif [[ "${REPLY[1]}" == "3" ]]; then
+		# Response code 3 means error. Likely too many colors requested.
+		returnvalue=-3
+	elif [[ "${REPLY[1]}" == "0" ]]; then
+		# 0 means okay. Yay!
+		returnvalue=${REPLY[2]}
+	else
+		# If we get here, response was not in the format we expected.
+		# Perhaps user typed during xterm response? Or cosmic rays?
+		returnvalue=-4
+	fi
 
-    echo $returnvalue
+	echo $returnvalue
 }
 
 waitforterminal() {
-    # Send an escape sequence and wait for a response from the terminal.
-    # This routine will let us know when an image transfer has finished
-    # and it's okay to send escape sequences that request results.
-    # (E.g., if we want to run resetnumcolors at the end of the program.)
-    # WARNING. While this should work with any terminal, if it fails,
-    # it'll end up waiting for approximately *forever* (i.e., 60 seconds).
-    read -s -t 60 -d "c" -p $'\e[c'
+	# Send an escape sequence and wait for a response from the terminal.
+	# This routine will let us know when an image transfer has finished
+	# and it's okay to send escape sequences that request results.
+	# (E.g., if we want to run resetnumcolors at the end of the program.)
+	# WARNING. While this should work with any terminal, if it fails,
+	# it'll end up waiting for approximately *forever* (i.e., 60 seconds).
+	read -s -t 60 -d "c" -p $'\e[c'
 }
-
 
 debugeta() {
-    # Given a number of bytes, estimate the amount of time its going
-    # to take to send at the current TTY baud rate.
-    # Mostly for larks as this will be completely bogus on terminal emulators.
+	# Given a number of bytes, estimate the amount of time its going
+	# to take to send at the current TTY baud rate.
+	# Mostly for larks as this will be completely bogus on terminal emulators.
 
-    len=$1
+	len=$1
 
-    # Static variables to store TTY type and STTY speed.
-    [[ "$TTY" ]] || TTY=$(tty)
-    [[ "$SPEED" ]] || SPEED=$(stty speed) || SPEED=0
+	# Static variables to store TTY type and STTY speed.
+	[[ "$TTY" ]] || TTY=$(tty)
+	[[ "$SPEED" ]] || SPEED=$(stty speed) || SPEED=0
 
-    echo "sixel command length is $len bytes"
+	echo "sixel command length is $len bytes"
 
-    if [[ "$SPEED" -gt 0 ]]; then
-	if [[ "$TTY" =~ /pt || "$TTY" =~ ttyp ]]; then
-	    echo "pseudoterminal detected (speed estimates only valid for real hardware)"
+	if [[ "$SPEED" -gt 0 ]]; then
+		if [[ "$TTY" =~ /pt || "$TTY" =~ ttyp ]]; then
+			echo "pseudoterminal detected (speed estimates only valid for real hardware)"
+		fi
+		echo "terminal speed is $SPEED bps"
+		echo "estimated time to send: $((len * 8 / SPEED)) seconds"
 	fi
-	echo "terminal speed is $SPEED bps"
-	echo "estimated time to send: $((len*8/SPEED)) seconds"
-    fi
 }
-
 
 # If the user hits ^C, we don't want them stuck in SIXEL mode
 cleanup() {
-    echo -n $'\e[?80h'		# Reenable sixel scrolling
-    echo -n $'\e\\'		# Escape sequence to stop SIXEL
-    exit 0
+	echo -n $'\e[?80h' # Reenable sixel scrolling
+	echo -n $'\e\\'    # Escape sequence to stop SIXEL
+	exit 0
 }
 trap cleanup SIGINT SIGHUP SIGABRT
-
 
 ######################################################################
 # MAIN BEGINS HERE
 ######################################################################
 
 if [ $# -eq 0 ]; then
-    usage
-    exit 1
+	usage
+	exit 1
 else
-    case "$1" in
-	-n|--num-colors) shift
-	    nflag="$1"
-	    shift
-	    # Just assume the palette is n colors. Do not bother checking or changing.
-	    # (Might be needed for some terminal emulators. I do not know.)
-	    if [[ "$nflag" -gt 0 ]]; then
-		default_numcolors=$nflag
-	    else
-		usage
-		exit 1
-	    fi
-	    ;;
-	-x|--force-xterm-colors) shift
-	    # Force xterm palette manipulation, regardless of $TERM 
-	    # (Might be needed for some terminal emulators. I do not know.)
-	    xflag=yup
-	    ;;
-	-X|--disable-xterm-colors) shift
-	    # Disable xterm palette manipulation, regardless of $TERM 
-	    # (Might be needed for some terminal emulators. I do not know.)
-	    Xflag=yup
-	    ;;
-	-*)
-	    usage
-	    exit 1
-	    ;;
-    esac
+	case "$1" in
+		-n | --num-colors)
+			shift
+			nflag="$1"
+			shift
+			# Just assume the palette is n colors. Do not bother checking or changing.
+			# (Might be needed for some terminal emulators. I do not know.)
+			if [[ "$nflag" -gt 0 ]]; then
+				default_numcolors=$nflag
+			else
+				usage
+				exit 1
+			fi
+			;;
+		-x | --force-xterm-colors)
+			shift
+			# Force xterm palette manipulation, regardless of $TERM
+			# (Might be needed for some terminal emulators. I do not know.)
+			xflag=yup
+			;;
+		-X | --disable-xterm-colors)
+			shift
+			# Disable xterm palette manipulation, regardless of $TERM
+			# (Might be needed for some terminal emulators. I do not know.)
+			Xflag=yup
+			;;
+		-*)
+			usage
+			exit 1
+			;;
+	esac
 fi
-
-
 
 numcolors=$default_numcolors
 
 # Optionally detect and set the number of palette colors
-if [[ "$xflag"  ||  -z "$Xflag" && -z "$nflag" && "$TERM" =~ ^xterm ]]; then
-    # Since the VT340 only had a palette of 16 colors, we can vastly
-    # improve the image if we tell xterm to increase it to 1024.
-    # This would fail on a real VT340.
-    palettechanged=yup
-    oldnumcolors=$(getnumcolors)
-    if [[ $oldnumcolors -lt 1024 ]]; then
-	numcolors=$(setnumcolors 1024)
-	if [[ $numcolors -le 0 ]]; then
-	    echo -e "\rTerminal did not accept escape sequence to increase color palette. Are you really an xterm?" >&2
-	    numcolors=$default_numcolors
+if [[ "$xflag" || -z "$Xflag" && -z "$nflag" && "$TERM" =~ ^xterm ]]; then
+	# Since the VT340 only had a palette of 16 colors, we can vastly
+	# improve the image if we tell xterm to increase it to 1024.
+	# This would fail on a real VT340.
+	palettechanged=yup
+	oldnumcolors=$(getnumcolors)
+	if [[ $oldnumcolors -lt 1024 ]]; then
+		numcolors=$(setnumcolors 1024)
+		if [[ $numcolors -le 0 ]]; then
+			echo -e "\rTerminal did not accept escape sequence to increase color palette. Are you really an xterm?" >&2
+			numcolors=$default_numcolors
+		fi
+	else
+		# At least 1024 colors, so do not change anything
+		numcolors=$oldnumcolors
+		palettechanged=
 	fi
-    else
-	# At least 1024 colors, so do not change anything
-	numcolors=$oldnumcolors
-	palettechanged=
-    fi
 fi
-
 
 # Small optimization (saves half a second)
 if [[ $numcolors == 1024 ]]; then
-    # Imagemagick already defaults to 1024 colors for sixel
-    colors=""
+	# Imagemagick already defaults to 1024 colors for sixel
+	colors=""
 else
-    colors="-colors $numcolors"
+	colors="-colors $numcolors"
 fi
-
 
 # Print image filename after showing it? Yes, if multiple files.
 if [[ $# -gt 1 ]]; then
-    showname=yup
+	showname=yup
 else
-    showname=""
+	showname=""
 fi
-
 
 # PAST IS PROLOGUE... NOW TO THE MEAT.
 for f; do
-    x=$(convert "$f" $geometry $colors sixel:- 2>/dev/null)
-    [[ ${#x} != 0 ]] || continue # The sixel command length better be >0 
+	x=$(convert "$f" $geometry $colors sixel:- 2>/dev/null)
+	[[ ${#x} != 0 ]] || continue # The sixel command length better be >0
 
-    : debugeta ${#x}
+	: debugeta ${#x}
 
-    case $0 in
-	*sixgif)
-	    # If this program is named "sixgif" play files as animations,
-	    # instead of displaying each frame and scrolling down.
-	    echo -n $'\e[?80l'	# Disable sixel scrolling
-	    for t in {1..3}; do
-		echo -n "$x"	# sixgif plays repeatedly
-	    done
-	    echo -n $'\e[?80h'	# Reenable sixel scrolling
-	    ;;
-	
-	*)
-	    echo -n "$x"	# sixcat just shows once
-	    [[ "$showname" ]] && echo "$f"
-	    ;;
-    esac
+	case $0 in
+		*sixgif)
+			# If this program is named "sixgif" play files as animations,
+			# instead of displaying each frame and scrolling down.
+			echo -n $'\e[?80l' # Disable sixel scrolling
+			for t in {1..3}; do
+				echo -n "$x" # sixgif plays repeatedly
+			done
+			echo -n $'\e[?80h' # Reenable sixel scrolling
+			;;
+
+		*)
+			echo -n "$x" # sixcat just shows once
+			[[ "$showname" ]] && echo "$f"
+			;;
+	esac
 done
-
 
 # TIDY UP
 waitforterminal
 if [[ "$palettechanged" ]]; then
-    # Reset color palette
-    numcolors=$(resetnumcolors)
-    : echo Number of colors reset to $numcolors >&2
+	# Reset color palette
+	numcolors=$(resetnumcolors)
+	: echo Number of colors reset to $numcolors >&2
 fi
